# Generated by Django 5.2.8 on 2025-11-24 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("status", models.IntegerField(choices=[(0, "Todo"), (1, "Done")])),
                ("note_id", models.UUIDField(null=True)),
            ],
        ),
    ]
